#ifndef CHARACTERISTICS_GLOBAL_HH
#define CHARACTERISTICS_GLOBAL_HH

#include <QtCore/qglobal.h>

#if defined(CHARACTERISTICS_LIBRARY)
#  define CHARACTERISTICS_EXPORT Q_DECL_EXPORT
#else
#  define CHARACTERISTICS_EXPORT Q_DECL_IMPORT
#endif

#endif // CHARACTERISTICS_GLOBAL_HH
